from django.db import models

class NHva01(models.Model):
	id = models.IntegerField(primary_key=True)
	hva01_tipo_documento = models.CharField(db_column='HVA01_TIPO_DOCUMENTO', max_length=1)  
	hva01_cedula = models.DecimalField(db_column='HVA01_CEDULA', max_digits=11, decimal_places=0)  
	hva01_nombre = models.CharField(db_column='HVA01_NOMBRE', max_length=60)  
	hva01_nro_carpeta = models.CharField(db_column='HVA01_NRO_CARPETA', max_length=10)  
	hva01_fecha_registro = models.DecimalField(db_column='HVA01_FECHA_REGISTRO', max_digits=8, decimal_places=0)  
	hva01_sexo = models.CharField(db_column='HVA01_SEXO', max_length=1)  
	hva01_libreta = models.CharField(db_column='HVA01_LIBRETA', max_length=10)  
	hva01_distrito = models.DecimalField(db_column='HVA01_DISTRITO', max_digits=3, decimal_places=0)  
	hva01_fecha_nacimiento = models.DecimalField(db_column='HVA01_FECHA_NACIMIENTO', max_digits=8, decimal_places=0)  
	hva01_lugar = models.CharField(db_column='HVA01_LUGAR', max_length=30)  
	hva01_profesion = models.CharField(db_column='HVA01_PROFESION', max_length=3)  
	hva01_direccion = models.CharField(db_column='HVA01_DIRECCION', max_length=40)  
	hva01_telefono_1 = models.CharField(db_column='HVA01_TELEFONO_1', max_length=10)  
	hva01_telefono_2 = models.CharField(db_column='HVA01_TELEFONO_2', max_length=10)  
	hva01_anos_primaria = models.DecimalField(db_column='HVA01_ANOS_PRIMARIA', max_digits=1, decimal_places=0)  
	hva01_anos_secundaria = models.DecimalField(db_column='HVA01_ANOS_SECUNDARIA', max_digits=1, decimal_places=0)  
	hva01_titulo_universitario = models.CharField(db_column='HVA01_TITULO_UNIVERSITARIO', max_length=1)  
	hva01_ciudad = models.CharField(db_column='HVA01_CIUDAD', max_length=30)  
	hva01_vetado = models.DecimalField(db_column='HVA01_VETADO', max_digits=1, decimal_places=0)  
	hva01_clave = models.CharField(db_column='HVA01_CLAVE', max_length=40)  
	hva01_perfil = models.IntegerField(db_column='HVA01_PERFIL')  
	hva01_actualiza = models.IntegerField(db_column='HVA01_ACTUALIZA')  
	hva02_observacion = models.CharField(db_column='HVA02_OBSERVACION', max_length=500)  
	hva03_barrio = models.CharField(db_column='HVA03_barrio', max_length=30)  
	hva03_localidad = models.CharField(db_column='HVA03_localidad', max_length=30)  
	hva03_zona = models.CharField(db_column='HVA03_zona', max_length=10)  
	hva03_expedida = models.CharField(db_column='HVA03_expedida', max_length=30)  
	hva03_email = models.CharField(db_column='HVA03_email', max_length=60)  
	hva03_nro_celular = models.CharField(db_column='HVA03_nro_celular', max_length=15)  
	hva03_nro_hijos = models.DecimalField(db_column='HVA03_nro_hijos', max_digits=2, decimal_places=0)  
	hva03_ficha_militar = models.CharField(max_length=20)
	hva03_f2 = models.CharField(max_length=20)
	hva03_certi_judicial = models.CharField(max_length=20)
	hva03_estatura = models.CharField(max_length=4)
	hva03_talla_uniforme = models.CharField(max_length=2)
	hva03_talla_camiza = models.CharField(max_length=2)
	hva03_talla_zapato = models.CharField(max_length=2)
	hva03_talla_gorra = models.CharField(max_length=2)
	hva03_estado_civil = models.CharField(max_length=1)
	hva03_grupo_rh = models.CharField(max_length=3)
	hva03_fecha_credencial = models.DecimalField(max_digits=8, decimal_places=0)
	hva03_clase_libreta = models.CharField(db_column='hva03_clase_LIBRETA', max_length=1)  
	hva03_benef_consecutivo1 = models.DecimalField(db_column='hva03_BENEF_CONSECUTIVO1', max_digits=2, decimal_places=0)  
	hva03_benef_nombre1 = models.CharField(db_column='hva03_BENEF_NOMBRE1', max_length=60)  
	hva03_benef_cedula1 = models.DecimalField(db_column='hva03_BENEF_CEDULA1', max_digits=11, decimal_places=0)  
	hva03_benef_fecha_nacimiento1 = models.DecimalField(db_column='hva03_BENEF_FECHA_NACIMIENTO1', max_digits=8, decimal_places=0)  
	hva03_benef_tipo1 = models.CharField(db_column='hva03_BENEF_TIPO1', max_length=1)  
	hva03_benef_sexo1 = models.CharField(db_column='hva03_BENEF_SEXO1', max_length=1)  
	hva03_benef_consecutivo2 = models.DecimalField(db_column='hva03_BENEF_CONSECUTIVO2', max_digits=2, decimal_places=0)  
	hva03_benef_nombre2 = models.CharField(db_column='hva03_BENEF_NOMBRE2', max_length=60)  
	hva03_benef_cedula2 = models.DecimalField(db_column='hva03_BENEF_CEDULA2', max_digits=11, decimal_places=0)  
	hva03_benef_fecha_nacimiento2 = models.DecimalField(db_column='hva03_BENEF_FECHA_NACIMIENTO2', max_digits=8, decimal_places=0)  
	hva03_benef_tipo2 = models.CharField(db_column='hva03_BENEF_TIPO2', max_length=1)  
	hva03_benef_sexo2 = models.CharField(db_column='hva03_BENEF_SEXO2', max_length=1)  
	hva03_benef_consecutivo3 = models.DecimalField(db_column='hva03_BENEF_CONSECUTIVO3', max_digits=2, decimal_places=0)  
	hva03_benef_nombre3 = models.CharField(db_column='hva03_BENEF_NOMBRE3', max_length=60)  
	hva03_benef_cedula3 = models.DecimalField(db_column='hva03_BENEF_CEDULA3', max_digits=11, decimal_places=0)  
	hva03_benef_fecha_nacimiento3 = models.DecimalField(db_column='hva03_BENEF_FECHA_NACIMIENTO3', max_digits=8, decimal_places=0)  
	hva03_benef_tipo3 = models.CharField(db_column='hva03_BENEF_TIPO3', max_length=1)  
	hva03_benef_sexo3 = models.CharField(db_column='hva03_BENEF_SEXO3', max_length=1)  
	hva03_benef_consecutivo4 = models.DecimalField(db_column='hva03_BENEF_CONSECUTIVO4', max_digits=2, decimal_places=0)  
	hva03_benef_nombre4 = models.CharField(db_column='hva03_BENEF_NOMBRE4', max_length=60)  
	hva03_benef_cedula4 = models.DecimalField(db_column='hva03_BENEF_CEDULA4', max_digits=11, decimal_places=0)  
	hva03_benef_fecha_nacimiento4 = models.DecimalField(db_column='hva03_BENEF_FECHA_NACIMIENTO4', max_digits=8, decimal_places=0)  
	hva03_benef_tipo4 = models.CharField(db_column='hva03_BENEF_TIPO4', max_length=1)  
	hva03_benef_sexo4 = models.CharField(db_column='hva03_BENEF_SEXO4', max_length=1)  
	hva03_benef_consecutivo5 = models.DecimalField(db_column='hva03_BENEF_CONSECUTIVO5', max_digits=2, decimal_places=0)  
	hva03_benef_nombre5 = models.CharField(db_column='hva03_BENEF_NOMBRE5', max_length=60)  
	hva03_benef_cedula5 = models.DecimalField(db_column='hva03_BENEF_CEDULA5', max_digits=11, decimal_places=0)  
	hva03_benef_fecha_nacimiento5 = models.DecimalField(db_column='hva03_BENEF_FECHA_NACIMIENTO5', max_digits=8, decimal_places=0)  
	hva03_benef_tipo5 = models.CharField(db_column='hva03_BENEF_TIPO5', max_length=1)  
	hva03_benef_sexo5 = models.CharField(db_column='hva03_BENEF_SEXO5', max_length=1)  
	hva03_benef_consecutivo6 = models.DecimalField(db_column='hva03_BENEF_CONSECUTIVO6', max_digits=2, decimal_places=0)  
	hva03_benef_nombre6 = models.CharField(db_column='hva03_BENEF_NOMBRE6', max_length=60)  
	hva03_benef_cedula6 = models.DecimalField(db_column='hva03_BENEF_CEDULA6', max_digits=11, decimal_places=0)  
	hva03_benef_fecha_nacimiento6 = models.DecimalField(db_column='hva03_BENEF_FECHA_NACIMIENTO6', max_digits=8, decimal_places=0)  
	hva03_benef_tipo6 = models.CharField(db_column='hva03_BENEF_TIPO6', max_length=1)  
	hva03_benef_sexo6 = models.CharField(db_column='hva03_BENEF_SEXO6', max_length=1)  
	hva01_primer_apellido = models.CharField(db_column='HVA01_PRIMER_APELLIDO', max_length=30)  
	hva01_segundo_apellido = models.CharField(db_column='HVA01_SEGUNDO_APELLIDO', max_length=30)  
	hva01_primer_nombre = models.CharField(db_column='HVA01_PRIMER_NOMBRE', max_length=30)  
	hva01_segundo_nombre = models.CharField(db_column='HVA01_SEGUNDO_NOMBRE', max_length=30)  
	hva01_nivel_educativo = models.CharField(db_column='HVA01_NIVEL_EDUCATIVO', max_length=30)  
	hva01_nucleo_formacion = models.CharField(db_column='HVA01_NUCLEO_FORMACION', max_length=60)  
	hva01_seleccionado_por = models.CharField(db_column='HVA01_SELECCIONADO_POR', max_length=20)  
	hva01_fecha_migracion = models.DecimalField(db_column='HVA01_FECHA_MIGRACION', max_digits=8, decimal_places=0)  		

	class Meta:        
		db_table = 'N_HVA01'