# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NHva01',
            fields=[
                ('id', models.IntegerField(serialize=False, primary_key=True)),
                ('hva01_tipo_documento', models.CharField(max_length=1, db_column=b'HVA01_TIPO_DOCUMENTO')),
                ('hva01_cedula', models.DecimalField(decimal_places=0, max_digits=11, db_column=b'HVA01_CEDULA')),
                ('hva01_nombre', models.CharField(max_length=60, db_column=b'HVA01_NOMBRE')),
                ('hva01_nro_carpeta', models.CharField(max_length=10, db_column=b'HVA01_NRO_CARPETA')),
                ('hva01_fecha_registro', models.DecimalField(decimal_places=0, max_digits=8, db_column=b'HVA01_FECHA_REGISTRO')),
                ('hva01_sexo', models.CharField(max_length=1, db_column=b'HVA01_SEXO')),
                ('hva01_libreta', models.CharField(max_length=10, db_column=b'HVA01_LIBRETA')),
                ('hva01_distrito', models.DecimalField(decimal_places=0, max_digits=3, db_column=b'HVA01_DISTRITO')),
                ('hva01_fecha_nacimiento', models.DecimalField(decimal_places=0, max_digits=8, db_column=b'HVA01_FECHA_NACIMIENTO')),
                ('hva01_lugar', models.CharField(max_length=30, db_column=b'HVA01_LUGAR')),
                ('hva01_profesion', models.CharField(max_length=3, db_column=b'HVA01_PROFESION')),
                ('hva01_direccion', models.CharField(max_length=40, db_column=b'HVA01_DIRECCION')),
                ('hva01_telefono_1', models.CharField(max_length=10, db_column=b'HVA01_TELEFONO_1')),
                ('hva01_telefono_2', models.CharField(max_length=10, db_column=b'HVA01_TELEFONO_2')),
                ('hva01_anos_primaria', models.DecimalField(decimal_places=0, max_digits=1, db_column=b'HVA01_ANOS_PRIMARIA')),
                ('hva01_anos_secundaria', models.DecimalField(decimal_places=0, max_digits=1, db_column=b'HVA01_ANOS_SECUNDARIA')),
                ('hva01_titulo_universitario', models.CharField(max_length=1, db_column=b'HVA01_TITULO_UNIVERSITARIO')),
                ('hva01_ciudad', models.CharField(max_length=30, db_column=b'HVA01_CIUDAD')),
                ('hva01_vetado', models.DecimalField(decimal_places=0, max_digits=1, db_column=b'HVA01_VETADO')),
                ('hva01_clave', models.CharField(max_length=40, db_column=b'HVA01_CLAVE')),
                ('hva01_perfil', models.IntegerField(db_column=b'HVA01_PERFIL')),
                ('hva01_actualiza', models.IntegerField(db_column=b'HVA01_ACTUALIZA')),
                ('hva02_observacion', models.CharField(max_length=500, db_column=b'HVA02_OBSERVACION')),
                ('hva03_barrio', models.CharField(max_length=30, db_column=b'HVA03_barrio')),
                ('hva03_localidad', models.CharField(max_length=30, db_column=b'HVA03_localidad')),
                ('hva03_zona', models.CharField(max_length=10, db_column=b'HVA03_zona')),
                ('hva03_expedida', models.CharField(max_length=30, db_column=b'HVA03_expedida')),
                ('hva03_email', models.CharField(max_length=60, db_column=b'HVA03_email')),
                ('hva03_nro_celular', models.CharField(max_length=15, db_column=b'HVA03_nro_celular')),
                ('hva03_nro_hijos', models.DecimalField(decimal_places=0, max_digits=2, db_column=b'HVA03_nro_hijos')),
                ('hva03_ficha_militar', models.CharField(max_length=20)),
                ('hva03_f2', models.CharField(max_length=20)),
                ('hva03_certi_judicial', models.CharField(max_length=20)),
                ('hva03_estatura', models.CharField(max_length=4)),
                ('hva03_talla_uniforme', models.CharField(max_length=2)),
                ('hva03_talla_camiza', models.CharField(max_length=2)),
                ('hva03_talla_zapato', models.CharField(max_length=2)),
                ('hva03_talla_gorra', models.CharField(max_length=2)),
                ('hva03_estado_civil', models.CharField(max_length=1)),
                ('hva03_grupo_rh', models.CharField(max_length=3)),
                ('hva03_fecha_credencial', models.DecimalField(max_digits=8, decimal_places=0)),
                ('hva03_clase_libreta', models.CharField(max_length=1, db_column=b'hva03_clase_LIBRETA')),
                ('hva03_benef_consecutivo1', models.DecimalField(decimal_places=0, max_digits=2, db_column=b'hva03_BENEF_CONSECUTIVO1')),
                ('hva03_benef_nombre1', models.CharField(max_length=60, db_column=b'hva03_BENEF_NOMBRE1')),
                ('hva03_benef_cedula1', models.DecimalField(decimal_places=0, max_digits=11, db_column=b'hva03_BENEF_CEDULA1')),
                ('hva03_benef_fecha_nacimiento1', models.DecimalField(decimal_places=0, max_digits=8, db_column=b'hva03_BENEF_FECHA_NACIMIENTO1')),
                ('hva03_benef_tipo1', models.CharField(max_length=1, db_column=b'hva03_BENEF_TIPO1')),
                ('hva03_benef_sexo1', models.CharField(max_length=1, db_column=b'hva03_BENEF_SEXO1')),
                ('hva03_benef_consecutivo2', models.DecimalField(decimal_places=0, max_digits=2, db_column=b'hva03_BENEF_CONSECUTIVO2')),
                ('hva03_benef_nombre2', models.CharField(max_length=60, db_column=b'hva03_BENEF_NOMBRE2')),
                ('hva03_benef_cedula2', models.DecimalField(decimal_places=0, max_digits=11, db_column=b'hva03_BENEF_CEDULA2')),
                ('hva03_benef_fecha_nacimiento2', models.DecimalField(decimal_places=0, max_digits=8, db_column=b'hva03_BENEF_FECHA_NACIMIENTO2')),
                ('hva03_benef_tipo2', models.CharField(max_length=1, db_column=b'hva03_BENEF_TIPO2')),
                ('hva03_benef_sexo2', models.CharField(max_length=1, db_column=b'hva03_BENEF_SEXO2')),
                ('hva03_benef_consecutivo3', models.DecimalField(decimal_places=0, max_digits=2, db_column=b'hva03_BENEF_CONSECUTIVO3')),
                ('hva03_benef_nombre3', models.CharField(max_length=60, db_column=b'hva03_BENEF_NOMBRE3')),
                ('hva03_benef_cedula3', models.DecimalField(decimal_places=0, max_digits=11, db_column=b'hva03_BENEF_CEDULA3')),
                ('hva03_benef_fecha_nacimiento3', models.DecimalField(decimal_places=0, max_digits=8, db_column=b'hva03_BENEF_FECHA_NACIMIENTO3')),
                ('hva03_benef_tipo3', models.CharField(max_length=1, db_column=b'hva03_BENEF_TIPO3')),
                ('hva03_benef_sexo3', models.CharField(max_length=1, db_column=b'hva03_BENEF_SEXO3')),
                ('hva03_benef_consecutivo4', models.DecimalField(decimal_places=0, max_digits=2, db_column=b'hva03_BENEF_CONSECUTIVO4')),
                ('hva03_benef_nombre4', models.CharField(max_length=60, db_column=b'hva03_BENEF_NOMBRE4')),
                ('hva03_benef_cedula4', models.DecimalField(decimal_places=0, max_digits=11, db_column=b'hva03_BENEF_CEDULA4')),
                ('hva03_benef_fecha_nacimiento4', models.DecimalField(decimal_places=0, max_digits=8, db_column=b'hva03_BENEF_FECHA_NACIMIENTO4')),
                ('hva03_benef_tipo4', models.CharField(max_length=1, db_column=b'hva03_BENEF_TIPO4')),
                ('hva03_benef_sexo4', models.CharField(max_length=1, db_column=b'hva03_BENEF_SEXO4')),
                ('hva03_benef_consecutivo5', models.DecimalField(decimal_places=0, max_digits=2, db_column=b'hva03_BENEF_CONSECUTIVO5')),
                ('hva03_benef_nombre5', models.CharField(max_length=60, db_column=b'hva03_BENEF_NOMBRE5')),
                ('hva03_benef_cedula5', models.DecimalField(decimal_places=0, max_digits=11, db_column=b'hva03_BENEF_CEDULA5')),
                ('hva03_benef_fecha_nacimiento5', models.DecimalField(decimal_places=0, max_digits=8, db_column=b'hva03_BENEF_FECHA_NACIMIENTO5')),
                ('hva03_benef_tipo5', models.CharField(max_length=1, db_column=b'hva03_BENEF_TIPO5')),
                ('hva03_benef_sexo5', models.CharField(max_length=1, db_column=b'hva03_BENEF_SEXO5')),
                ('hva03_benef_consecutivo6', models.DecimalField(decimal_places=0, max_digits=2, db_column=b'hva03_BENEF_CONSECUTIVO6')),
                ('hva03_benef_nombre6', models.CharField(max_length=60, db_column=b'hva03_BENEF_NOMBRE6')),
                ('hva03_benef_cedula6', models.DecimalField(decimal_places=0, max_digits=11, db_column=b'hva03_BENEF_CEDULA6')),
                ('hva03_benef_fecha_nacimiento6', models.DecimalField(decimal_places=0, max_digits=8, db_column=b'hva03_BENEF_FECHA_NACIMIENTO6')),
                ('hva03_benef_tipo6', models.CharField(max_length=1, db_column=b'hva03_BENEF_TIPO6')),
                ('hva03_benef_sexo6', models.CharField(max_length=1, db_column=b'hva03_BENEF_SEXO6')),
                ('hva01_primer_apellido', models.CharField(max_length=30, db_column=b'HVA01_PRIMER_APELLIDO')),
                ('hva01_segundo_apellido', models.CharField(max_length=30, db_column=b'HVA01_SEGUNDO_APELLIDO')),
                ('hva01_primer_nombre', models.CharField(max_length=30, db_column=b'HVA01_PRIMER_NOMBRE')),
                ('hva01_segundo_nombre', models.CharField(max_length=30, db_column=b'HVA01_SEGUNDO_NOMBRE')),
                ('hva01_nivel_educativo', models.CharField(max_length=30, db_column=b'HVA01_NIVEL_EDUCATIVO')),
                ('hva01_nucleo_formacion', models.CharField(max_length=60, db_column=b'HVA01_NUCLEO_FORMACION')),
                ('hva01_seleccionado_por', models.CharField(max_length=20, db_column=b'HVA01_SELECCIONADO_POR')),
                ('hva01_fecha_migracion', models.DecimalField(decimal_places=0, max_digits=8, db_column=b'HVA01_FECHA_MIGRACION')),
            ],
            options={
                'db_table': 'N_HVA01',
            },
        ),
    ]
